backend:
  name: github
  repo: mangaduy/portfolio-aduy
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth
  site_domain: yudhaaduy.netlify.app
  site_id: 2af77c4d-a675-4e96-90d6-6539f7edc83c
  
media_folder: assets
public_folder: assets

collections:
  - name: config
    label: Data Portofolio
    files:
      - file: config.json
        label: Konten Utama
        name: main
        fields:
          - label: Headline Atas
            name: headline
            widget: string
          - label: Tentang Saya (Bio)
            name: about
            widget: markdown
          - label: Pengaturan Fitur
            name: settings
            widget: object
            fields:
              - label: Tampilkan Tombol PDF
                name: show_pdf
                widget: boolean
              - label: Tampilkan Tombol Booking
                name: show_booking
                widget: boolean
              - label: Link Tally Form
                name: tally_url
                widget: string
          - label: Seksi Portofolio
            name: sections
            widget: list
            fields:
              - label: Nama Seksi
                name: name
                widget: string
              - label: Daftar Item
                name: items
                widget: list
                fields:
                  - label: Tahun
                    name: year
                    widget: string
                  - label: Judul
                    name: title
                    widget: string
                  - label: Deskripsi
                    name: desc
                    widget: markdown
                  - label: Link Media
                    name: video
                    widget: string
                    required: false
          - label: Branding & Footer
            name: branding
            widget: object
            fields:
              - label: Nama Tampilan Atas/Bawah
                name: footer_name
                widget: string
              - label: Teks Copyright
                name: copyright
                widget: string
